from .animal.terrestrial import ITerrestrial
from .animal.aquatic import IAquatic
from .animal.flying import IFlying
from .animal.walking import IWalking
from .animal.swimming import ISwimming
from .animal.saltwater import ISaltwater
from .animal.freshwater import IFreshwater
from .habitat.environmentCharacteristics import IEnviroChar
from .habitat.stagnant import IStagnant
from .habitat.contains_animals import IContainsAnimals
from .habitat.contains_plants import IContainsPlants
from .identifiable import Identifiable
from .hospitable import IHospitable
